# CS165 Team Activity 04 - Stretch
# Written by Chad Macbeth

# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : rational.h rational.cpp ta04.cpp
	g++ rational.cpp ta04.cpp

