###############################################################
# Program:
#     Checkpoint 04B,  Date 
#     Brother Macbeth, CS165
# Author:
#     your name here
# Summary:
#     Put your summary code here... 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : date.h date.cpp check04b.cpp
	g++ date.cpp check04b.cpp

